<?php

use Illuminate\Database\Seeder;
use App\Product;
use App\Inventory;

class InventorySeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
      //
      if (Inventory::count() == 0) {
        //
        Inventory::create([ #1
          'category_id' => 13,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Mountain Bike  1x12',
          'description' => 'BICICLETA SCOTT SCALE 965 2022',
          'company_name' => 'SCOTT',
          'image' => 'Scott Bicicleta MTB.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #2
          'category_id' => 3,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'MacBook Air',
          'description' => 'MacBook Air 13" con Chip M1 (2020) 256 GB - Inglés - Gris Espacial',
          'company_name' => 'APPLE',
          'image' => 'Apple MacBook Air.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #3
          'category_id' => 1,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Expresso Coffee Machine',
          'description' => 'SMEG Retro Style Espresso Coffee Machine - Red',
          'company_name' => 'SMEG',
          'image' => 'surface_pro_x.png',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #4
          'category_id' => 1,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => ' Smart LED',
          'description' => 'Sony Televisor LED / KD-65X80J / 65"',
          'company_name' => 'SONY',
          'image' => 'Pantalla sony X850E _ LED _ 4K Ultra HD -65.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #5
          'category_id' => 5,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'iPhone 13',
          'description' => 'iPhone 13 - 128GB - Blanco',
          'company_name' => 'APPLE',
          'image' => 'Apple iPhone 13.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #6
          'category_id' => 13,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'BiciMoto Eléctrica',
          'description' => 'Katana Bicimoto Eléctrica / EASY PRO / 800 W',
          'company_name' => 'KATANA',
          'image' => 'Katana Bicimoto Electrica.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #7
          'category_id' => 8,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'PS5 Console',
          'description' => 'Sony Consola PlayStation 5 / PS5 / 4K',
          'company_name' => 'SONY',
          'image' => 'Sony PS5.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #8
          'category_id' => 4,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'iPad Air',
          'description' => 'iPad Air 10.9 5ta Generación - 64GB - Azul',
          'company_name' => 'APPLE',
          'image' => 'Apple IpadAir.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #9
          'category_id' => 14,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Caminadora',
          'description' => 'Proform Caminadora Eléctrica / PFTL59720 / 300 Libras',
          'company_name' => 'PROFORM',
          'image' => 'Caminadora.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #10
          'category_id' => 15,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Sofá masajeador',
          'description' => 'Sillón relax 8 puntos de masaje 88x93x104 cm',
          'company_name' => 'N/D',
          'image' => 'Sillon Masajeador.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #11
          'category_id' => 10,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Apple Watch Gen 7',
          'description' => 'Apple Watch Series 7 GPS (45mm) Azul',
          'company_name' => 'APPLE',
          'image' => 'Apple iWatch.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #12
          'category_id' => 13,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Bicicleta Estacionaria',
          'description' => 'Bicicleta Spinning, volante inercia 13kg, ultrasilenciosa',
          'company_name' => 'N/D',
          'image' => 'Bicicleta Spinning.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #13
          'category_id' => 8,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => ' PS4 Console',
          'description' => 'Sony Consola PS4 / 3 HITS + / 1TB',
          'company_name' => 'SONY',
          'image' => 'Sony PS4.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #14
          'category_id' => 8,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Gafas de Realidad Virtual',
          'description' => 'Oculus Quest 2, 128GB',
          'company_name' => 'OCULUS',
          'image' => 'Oculus Quest .jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #15
          'category_id' => 11,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Drone Bugs 16 PRO',
          'description' => 'DRONE Bugs 16 PRO,Gimbal 3ejes + EIS, 4K Sony, 1.2 Km Alcance',
          'company_name' => 'BUGS',
          'image' => 'Drone Bug 16 Pro.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #16
          'category_id' => 14,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Press de Banca',
          'description' => 'Press de Banca, 5 alturas, 4 niveles de inclinación: 8º, 0º, 15º y 30º',
          'company_name' => 'N/D',
          'image' => 'Pres de Banca.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #17
          'category_id' => 7,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Harman Kardon Parlante',
          'description' => 'Parlante Harman Kardon Onyx Studio 7 - Negro',
          'company_name' => 'HARMAN',
          'image' => 'Harman Cardon Parlante.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #18
          'category_id' => 15,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Sofá reclinable',
          'description' => 'Commodity Sofá reclinable / 73012BD-91BR / Café',
          'company_name' => 'COMMODITY',
          'image' => 'Sofa Reclinable.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #19
          'category_id' => 16,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Columbia Jacket Impermeable',
          'description' => 'Jacket Impermeable para hombre Eager Air Interchange',
          'company_name' => 'COLUMBIA',
          'image' => 'Columbia Jacket Impermeable.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #20
          'category_id' => 17,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Set 3 Maletas',
          'description' => 'Maleta dura, 100% Polieste. Set contiene maletas de 20", 24" y 28".',
          'company_name' => 'N/D',
          'image' => 'Set Maletas x3.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #21
          'category_id' => 15,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Silla Gamer',
          'description' => 'Silla Gaming iGAMING Elite X - Amarilla con Negro',
          'company_name' => 'IGAMING',
          'image' => 'Silla Gaming.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #22
          'category_id' => 7,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'AirPods',
          'description' => 'Apple AirPods with Charging Case',
          'company_name' => 'APPLE',
          'image' => 'Apple AirPods.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #23
          'category_id' => 7,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'JBL Audífonos',
          'description' => 'Audífonos JBL T750BT Cancelación de ruido BT - Negro',
          'company_name' => 'JBL',
          'image' => 'JBL AUDIFONOS.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #24
          'category_id' => 14,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Kettlebells 20kg',
          'description' => 'Kettle bell 20 kg',
          'company_name' => 'N/D',
          'image' => 'Kettle bell 20 kg.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #25
          'category_id' => 13,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Rack para 3 bicicletas',
          'description' => 'RACK BUZZ BEETLE 3 BICICS BC814-3HH BUZZ-RACK',
          'company_name' => 'N/D',
          'image' => 'Rack Bicicleta x3.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #26
          'category_id' => 14,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Kettlebells 16kg',
          'description' => 'Kettle bell 16 kg',
          'company_name' => 'N/D',
          'image' => 'Kettle bell 16 kg.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #27
          'category_id' => 17,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Tienda de Campaña',
          'description' => 'Tienda vinil impermeable, 6 personas',
          'company_name' => 'N/D',
          'image' => 'Tienda de Campaña.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #28
          'category_id' => 16,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Columbia chaleco mujer',
          'description' => 'Chaleco Fleece para mujer PFG Harborside',
          'company_name' => 'COLUMBIA',
          'image' => 'Columbia Chaleco Mujer.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #29
          'category_id' => 16,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Columbia camisa manga larga',
          'description' => 'Camisa para hombre PFG Half Moon manga larga',
          'company_name' => 'COLUMBIA',
          'image' => 'Columbia Camisa manga larga.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #30
          'category_id' => 16,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Columbia blusa manga larga',
          'description' => 'Camisa para mujer PFG Bahama manga larga',
          'company_name' => 'COLUMBIA',
          'image' => 'Columbia Blusa manga larga.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #31
          'category_id' => 12,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Wilson Raqueta Tennis',
          'description' => 'Raqueta Tennis BLX Tour 95"',
          'company_name' => 'WILSON',
          'image' => 'Raqueta Wilson.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #32
          'category_id' => 14,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Kettlebells 10kg',
          'description' => 'Kettle bell 10 kg',
          'company_name' => 'N/D',
          'image' => 'Kettle bell 10 kg.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #33
          'category_id' => 15,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Silla Plegable',
          'description' => 'Silla Plegable Ecology, Confort Gris, Playa y Montaña',
          'company_name' => 'ECOLOGY',
          'image' => 'SILLA ECOLOGY.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #34
          'category_id' => 12,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Wilson Backpack',
          'description' => 'Salveque Wilson Tennis',
          'company_name' => 'WILSON',
          'image' => 'SILLA ECOLOGY.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #35
          'category_id' => 17,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'TKWide Botella 20 onzas',
          'description' => '20 onzas aislada al vacío, agua, café, deportiva, aislada',
          'company_name' => 'TKWIDE',
          'image' => 'TKWide Botella.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #36
          'category_id' => 12,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Head Backpack',
          'description' => 'BACKPACK KIDS BLUE',
          'company_name' => 'N/D',
          'image' => 'Head Raqueta Backpack.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #37
          'category_id' => 18,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Alfombras de invierno automóvil x5',
          'description' => 'Alfombra negra adrian de caucho 5 piezas',
          'company_name' => 'N/D',
          'image' => 'Alfombras Invierno x5.webp',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);
        Inventory::create([ #38
          'category_id' => 17,
          'product_id' => 1,
          'company_id' => NULL,
          'point_id' => NULL,
          'name' => 'Klean Kanteen Botella de agua',
          'description' => 'CLASSIC 27OZ CAP 3.0 SS / Naranja',
          'company_name' => 'KLEAN',
          'image' => 'KleanKantine Botella Naranja.jpeg',
          'classification' => '',
          'unit_measurement' => 'Unid',
          'qmin' => 0,
          'qmax' => 0,
          'existence' => 0,
          'availability' => 0,
          'is_active' => true,
          'note' => 'Pre-Registro',
        ]);

      }
  }
}
